name: Nuke CICD Pipeline
on:
  push:
    branches:
    - prerelease
    - master
    tags:
    - bump-*
  pull_request:
    branches:
    - '**'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  PRE_SETUP:
    name: Pre Setup
    runs-on:
      labels: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
        submodules: recursive
        persist-credentials: true
    - id: NUKE_RUN
      name: Run Nuke PipelinePreSetup
      run: chmod +x ./build.sh && ./build.sh PipelinePreSetup
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    timeout-minutes: 10
    outputs:
      NUKE_PRE_SETUP: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP }}
      NUKE_PRE_SETUP_OUTPUT_TEST_MATRIX: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_OUTPUT_TEST_MATRIX }}
      NUKE_PRE_SETUP_OUTPUT_BUILD_MATRIX: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_OUTPUT_BUILD_MATRIX }}
      NUKE_PRE_SETUP_OUTPUT_PUBLISH_MATRIX: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_OUTPUT_PUBLISH_MATRIX }}
      NUKE_PRE_SETUP_LOCKERHELPERSBUILD_CONDITION: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_LOCKERHELPERSBUILD_CONDITION }}
      NUKE_PRE_SETUP_LOCKERHELPERSBUILD_RUNS_ON: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_LOCKERHELPERSBUILD_RUNS_ON }}
      NUKE_PRE_SETUP_LOCKERHELPERSBUILD_RUN_SCRIPT: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_LOCKERHELPERSBUILD_RUN_SCRIPT }}
      NUKE_PRE_SETUP_LOCKERHELPERSBUILD_CACHE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_LOCKERHELPERSBUILD_CACHE_KEY }}
      NUKE_PRE_SETUP_LOCKERHELPERSBUILD_CACHE_RESTORE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_LOCKERHELPERSBUILD_CACHE_RESTORE_KEY }}
      NUKE_PRE_SETUP_LOCKERHELPERSBUILD_CACHE_MAIN_RESTORE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_LOCKERHELPERSBUILD_CACHE_MAIN_RESTORE_KEY }}
      NUKE_PRE_SETUP_LOCKERHELPERSBUILD_CHECKOUT_FETCH_DEPTH: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_LOCKERHELPERSBUILD_CHECKOUT_FETCH_DEPTH }}
      NUKE_PRE_SETUP_LOCKERHELPERSBUILD_CHECKOUT_FETCH_TAGS: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_LOCKERHELPERSBUILD_CHECKOUT_FETCH_TAGS }}
      NUKE_PRE_SETUP_LOCKERHELPERSBUILD_CHECKOUT_SUBMODULES: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_LOCKERHELPERSBUILD_CHECKOUT_SUBMODULES }}
      NUKE_PRE_SETUP_LOCKERHELPERSPUBLISH_CONDITION: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_LOCKERHELPERSPUBLISH_CONDITION }}
      NUKE_PRE_SETUP_LOCKERHELPERSPUBLISH_RUNS_ON: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_LOCKERHELPERSPUBLISH_RUNS_ON }}
      NUKE_PRE_SETUP_LOCKERHELPERSPUBLISH_RUN_SCRIPT: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_LOCKERHELPERSPUBLISH_RUN_SCRIPT }}
      NUKE_PRE_SETUP_LOCKERHELPERSPUBLISH_CACHE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_LOCKERHELPERSPUBLISH_CACHE_KEY }}
      NUKE_PRE_SETUP_LOCKERHELPERSPUBLISH_CACHE_RESTORE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_LOCKERHELPERSPUBLISH_CACHE_RESTORE_KEY }}
      NUKE_PRE_SETUP_LOCKERHELPERSPUBLISH_CACHE_MAIN_RESTORE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_LOCKERHELPERSPUBLISH_CACHE_MAIN_RESTORE_KEY }}
      NUKE_PRE_SETUP_LOCKERHELPERSPUBLISH_CHECKOUT_FETCH_DEPTH: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_LOCKERHELPERSPUBLISH_CHECKOUT_FETCH_DEPTH }}
      NUKE_PRE_SETUP_LOCKERHELPERSPUBLISH_CHECKOUT_FETCH_TAGS: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_LOCKERHELPERSPUBLISH_CHECKOUT_FETCH_TAGS }}
      NUKE_PRE_SETUP_LOCKERHELPERSPUBLISH_CHECKOUT_SUBMODULES: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_LOCKERHELPERSPUBLISH_CHECKOUT_SUBMODULES }}
  LOCKERHELPERSBUILD:
    name: Build - locker_helpers (LockerHelpersBuild)
    runs-on: ${{ fromJson(needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_LOCKERHELPERSBUILD_RUNS_ON) }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_LOCKERHELPERSBUILD_CHECKOUT_FETCH_DEPTH }}
        fetch-tags: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_LOCKERHELPERSBUILD_CHECKOUT_FETCH_TAGS }}
        submodules: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_LOCKERHELPERSBUILD_CHECKOUT_SUBMODULES }}
        persist-credentials: true
    - name: Cache Run
      uses: actions/cache@v4
      with:
        path: ./.nuke/temp/cache
        key: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_LOCKERHELPERSBUILD_CACHE_KEY }}
        restore-keys: |-
          ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_LOCKERHELPERSBUILD_CACHE_RESTORE_KEY }}
          ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_LOCKERHELPERSBUILD_CACHE_MAIN_RESTORE_KEY }}
    - id: NUKE_RUN
      name: Run Nuke PipelineRunEntry
      run: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_LOCKERHELPERSBUILD_RUN_SCRIPT }} PipelineRunEntry --args "run=build;idsToRun=LockerHelpersBuild"
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: locker_helpers___LOCKERHELPERSBUILD
        path: ./.nuke/temp/artifacts/*
        if-no-files-found: error
        retention-days: 1
    needs:
    - PRE_SETUP
    if: "! failure() && ! cancelled() && needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_LOCKERHELPERSBUILD_CONDITION == 'true'"
    env:
      NUKE_PRE_SETUP: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP }}
  LOCKERHELPERSPUBLISH:
    name: Publish - locker_helpers (LockerHelpersPublish)
    runs-on: ${{ fromJson(needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_LOCKERHELPERSPUBLISH_RUNS_ON) }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_LOCKERHELPERSPUBLISH_CHECKOUT_FETCH_DEPTH }}
        fetch-tags: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_LOCKERHELPERSPUBLISH_CHECKOUT_FETCH_TAGS }}
        submodules: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_LOCKERHELPERSPUBLISH_CHECKOUT_SUBMODULES }}
        persist-credentials: true
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./.nuke/temp/artifacts-download
        pattern: locker_helpers___*
    - name: Cache Run
      uses: actions/cache@v4
      with:
        path: ./.nuke/temp/cache
        key: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_LOCKERHELPERSPUBLISH_CACHE_KEY }}
        restore-keys: |-
          ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_LOCKERHELPERSPUBLISH_CACHE_RESTORE_KEY }}
          ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_LOCKERHELPERSPUBLISH_CACHE_MAIN_RESTORE_KEY }}
    - id: NUKE_RUN
      name: Run Nuke PipelineRunEntry
      run: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_LOCKERHELPERSPUBLISH_RUN_SCRIPT }} PipelineRunEntry --args "run=publish;idsToRun=LockerHelpersPublish"
    needs:
    - PRE_SETUP
    - LOCKERHELPERSBUILD
    if: "! failure() && ! cancelled() && needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_LOCKERHELPERSPUBLISH_CONDITION == 'true' && needs.LOCKERHELPERSBUILD.result == 'success'"
    env:
      NUKE_PRE_SETUP: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP }}
  POST_SETUP:
    name: Post Setup
    runs-on:
      labels: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
        submodules: recursive
        persist-credentials: true
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./.nuke/temp/artifacts-download
    - name: Run Nuke PipelinePostSetup
      run: chmod +x ./build.sh && ./build.sh PipelinePostSetup
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    needs:
    - PRE_SETUP
    - LOCKERHELPERSBUILD
    - LOCKERHELPERSPUBLISH
    if: success() || failure() || always()
    timeout-minutes: 10
    env:
      NUKE_PRE_SETUP: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP }}
      NUKE_RUN_RESULT_GITHUB_LOCKERHELPERSBUILD: ${{ needs.LOCKERHELPERSBUILD.result }}
      NUKE_RUN_RESULT_GITHUB_LOCKERHELPERSPUBLISH: ${{ needs.LOCKERHELPERSPUBLISH.result }}
env:
  NUKE_NUGET_AUTH_TOKEN: ${{ secrets.NUGET_AUTH_TOKEN }}
  NUKE_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
